import Head from 'next/head'
import React, {useEffect, useState} from 'react'
import {  Col, Collapse, InputNumber, Rate, Row, Space } from 'antd';
import Button from "../../components/Button"
import {Image as ImageAnt} from 'antd'
import style from "./ProductDetail.module.scss"
import classNames from 'classnames/bind';
import Image from 'next/image';
import index from '../../pages/our-menu';
import { DollarCircleOutlined, MinusOutlined, PlusOutlined } from '@ant-design/icons';
import Product from '../../components/product';

const cx = classNames.bind(style)
export default function ProductDetail() {
   
        const serverImages = [
            
            require("../../assets/imgs/product-img-2.jpg"),
            require("../../assets/imgs/product-img-3.jpg"),
            require("../../assets/imgs/product-img-1.jpg")
        
        ];

    
  return (
    <>
        <Head >
            <title>Fooce | Smoothie</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/icon.png" />
        </Head>
        <Row justify={"center"} className={cx("product-detail")} gutter={80} >
            <Col span={8} className="gutter-row">
                <div className={cx("product-gallery")}>
                   
                        <div className={cx("product-img-wrap")}>
                        <Image src={require("../../assets/imgs/product-img-4.jpg")} alt="product-img"  className={cx("img-origin")}/>
                        </div>
                        <div className={cx("img-group")}>
                            <ImageAnt.PreviewGroup >
                                
                                    {serverImages.map((imageUrl, index) => (
                                
                                            <ImageAnt
                                                key={index}
                                                src={imageUrl.default.src}
                                                width={175}
                                                className={cx("img-thumbnail")}
                                                style={{borderRadius: "4px", overflow: "hidden"}}
                                            />
                             
                                        
                                ))}
                            
                            
                        </ImageAnt.PreviewGroup>
                        </div>
                        
                    </div>
                    
               
            </Col>
            <Col span={8} className="gutter-row">
                <div className={cx("product-name")}>
                Strawesome Smoothie
                </div>
                <div className={cx("product-price")}>
                    <DollarCircleOutlined style={{fontSize:"14px", color: "#5a5a5a", transform: "translateY(100%)"}}/>
                    <span className={cx("price")}>14.00</span>

                </div>
                <div className={cx("product-rate")}>
                    <Rate disabled defaultValue={4} style={{color: "#FBBCC0", fontSize: "12px"}}/>
                    <span className={cx("number-rate")}>(1 customer review)</span>
                </div>
                <div className={cx("product-intro")}>
                    Proin gravida nibh vel velit auctor aliquet. 
                    Aenean sollicitudin, lorem quis bibendum auctor, 
                    nisi elit consequat ipsum, nec sagittis sem. Nibh id elit. 
                    Duis sed odio sit amet nibh vulputate cursus a sit amet mauris.
                </div>
                <div className={cx("product-order")}>
                    <InputNumber  min={1} max={10} defaultValue={1} className={cx("input-number")}  />
                    <Button name = "add to cart" />
                </div>
                <div className={cx("product-infor")}>
                    <div className={cx("infor-wrap")}>
                        <span className={cx("infor-title")}>SKU:</span>
                        <span className={cx("infor-text")}>005</span>
                    </div>
                    <div className={cx("infor-wrap")}>
                        <span className={cx("infor-title")}>Category:</span>
                        <span className={cx("infor-text")}>Smoothie</span>
                    </div>
                    <div className={cx("infor-wrap")}>
                        <span className={cx("infor-title")}>Tags:</span>
                        <span className={cx("infor-text")}>Fruit</span>
                    </div>
                </div>
                <div >
                <Collapse  expandIcon= {customExpandIcon} className={cx("product-description")}>
                    <Collapse.Panel header={<CustomHeader>Description</CustomHeader>} key="1" className={cx("description")}>
                    <div className={cx("infor-wrap")}>
                        <div className={cx("infor-text")}>
                            Proin gravida nibh vel velit auctor aliquet. 
                            Aenean sollicitudin, lorem quis bibendum auctor, 
                            nisi elit consequat ipsum, nec sagittis sem. Nibh id elit. 
                            Duis sed odio sit amet nibh vulputate cursus a sit amet mauris.
                        </div>
                    </div>
                    </Collapse.Panel>
                    <Collapse.Panel header={<CustomHeader>Additional information</CustomHeader>}  key="2" className={cx("description")}>
                        <div className={cx("infor-wrap")}>
                            <span className={cx("infor-title")}>Weight:</span>
                            <span className={cx("infor-text")}>	12 kg</span>
                        </div>
                        <div className={cx("infor-wrap")}>
                            <span className={cx("infor-title")}>Dimensions:</span>
                            <span className={cx("infor-text")}>20 × 20 × 10 cm</span>
                        </div>
                    </Collapse.Panel>
                    <Collapse.Panel header={<CustomHeader>Reviews</CustomHeader>} key="3" className={cx("description")}>
                        <div className={cx("review-wrap")}>
                            <div className={cx("review-title")}>1 review for Strawesome Smoothie</div>
                            <div className={cx("review")}>
                                <div className={cx("review-img-wrap")}>
                                    <Image src={require("../../assets/imgs/jisoo.jpg")} alt="reviewer" className={cx("reviewer-img")} />
                                </div>
                                <div className={cx("review-content")}>
                                    
                                    <Rate disabled defaultValue={4} className={cx("review-star")} style={{color: "#FBBCC0", fontSize: "13px"}}/>
                                    <div className={cx("review-name")}>Jisoo Kim</div>
                                    <div className={cx("review-text")}>
                                        Lorem ipsum dolor sit amet, consectetur adipiscing elit. 
                                        Suspendisse non mi non nisl pulvinar aliquet. Morbi aliquet tortor ac metus bibendum, 
                                        vel sollicitudin lectus mattis.
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div className={cx("your-review")}>
                            <div className={cx("your-review-title")}>Add a review</div>
                            <div className={cx("your-review-title")}>Your Rating</div>
                            <Rate style={{color: "#FBBCC0", fontSize: "13px"}}/>
                            <div className={cx("your-review-title")}>Your Review</div>
                            <textarea className={cx("your-review-input")}/>
                            <Button name="submit" />
                        </div>
                    </Collapse.Panel>
                </Collapse>
                </div>
            </Col>
        </Row>
        <div className={cx("product-suggest")}>
            <div className={cx("suggest-product")}>Related products</div>
            <Row gutter={16}>
                <Product name = {"juice-2"}/>
                <Product name = {"juice-2"}/>
                <Product name = {"juice-2"}/>
                <Product name = {"juice-2"}/>
            </Row>
            
        </div>
    </>
  )
}

const CustomHeader = ({children}) => {
    return (
        <span className={cx("descripttion-title")}>
            {children}
        </span>
    )
}

const customExpandIcon = (panelProps) => {
    const { isActive } = panelProps;
    return isActive ? <MinusOutlined /> : <PlusOutlined />;
};

