import style from "./Layout.module.scss"
import Header from "../../components/Header";
import classNames from "classnames/bind";
import Footer from "../../components/Footer";
import Head from "next/head";


const cx = classNames.bind(style)
function Layout({children}) {
    return ( 
        <>
        <Head>
            <title>Fooce</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/icon.png" />
        </Head>
        <div className={cx("app")}>
            <div className={cx("header")} >
                <Header />
            </div>
            <div className={cx("container")}>
                {children}
            </div>
            <div className={cx("footer")}>
                <Footer />
            </div>
        </div>
        
        </>
        
     )
}

export default Layout;