import { DollarCircleOutlined } from '@ant-design/icons'
import { Button, Row, Table } from 'antd'
import { ColumnsType } from 'antd/es/table'
import Head from 'next/head'
import React from 'react'
import PageTitle from '../../components/PageTitle'
import TotalMoney from '../../module/admin/components/total-money/TotalMoney'
import classNames from 'classnames/bind'
import style from "./Admin.module.scss"
interface DataType {
  key: string,
  order: string,
  date: string,
  status: string,
  total: number

}

const columns: ColumnsType<DataType> = [
  {
      title: 'Order',
      dataIndex: 'order',
      key: 'order',
      render: (order) => <span>{order}</span>

  },
  {
      title: 'Date',
      dataIndex: 'date',
      key: 'date',
      render: (date) => <span>{date}</span>
  },
  {
      title: 'Status',
      dataIndex: 'status',
      key: 'status',
      render: (value) => <span>{value}</span>
  },
  {
      title: 'Total',
      dataIndex: 'total',
      key: 'total',
      render: (value) => <span>
          <DollarCircleOutlined />
          {value}
          </span>
  },
  {
      title: 'Actions',
      dataIndex: 'action',
      key: 'action',
      render: (_, record) => {
          return (
              <Button>view</Button>
          )
      }
  },
]

const dataSource: DataType[] = [
  {
      key: '1',
      order: '#26112',
      date: '26-07-2022',
      status: 'hold on',
      total: 1000000

  },
  {
      key: '2',
      order: '#26112',
      date: '26-07-2022',
      status: 'hold on',
      total: 1000000

  },{
      key: '2',
      order: '#26112',
      date: '26-07-2022',
      status: 'hold on',
      total: 1000000

  }
]


const cx = classNames.bind(style)
function DashboardAdmin() {
  return (
    <div>
        <>
        <Head >
            <title>Fooce | Admin - Dashboard</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/icon.png" />
        </Head>
        <PageTitle name = "Admin - Dashboard" />
            <div className={cx('admin')}>
                <Row gutter={16} style={{marginBottom: '40px'}}>
                    <TotalMoney name="Tổng tiền trong ngày" totalMoney='2000000'/>
                    <TotalMoney name="Tổng tiền trong tuần" totalMoney='3000000'/>
                    <TotalMoney name="Tổng tiền trong tháng" totalMoney='4000000'/>
                    <TotalMoney name="Tổng tiền trong năm" totalMoney='5000000'/>
                </Row>
                <Table dataSource={dataSource} columns={columns} />
            </div>
        </>
    </div>
  )
}

export default DashboardAdmin;
