import React from 'react'
import classNames from 'classnames/bind'
import style from "./Admin.module.scss"
import Head from 'next/head'
import PageTitle from '../../components/PageTitle'
import { TabsProps } from 'antd'

const cx = classNames.bind(style)

const items: TabsProps['items'] = [
    {
        key: '1',
        label: (<span className={cx("tab-header")}>Dashboard</span>),
        children: (
            <>
            </>
        )
    }
]
export default function Admin() {
  return (
    <>
        <Head >
            <title>Fooce | Admin</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/icon.png" />
        </Head>
        <PageTitle name = "Admin" />

    </>
  )
}
