import React from 'react'
import PageTitle from '../../components/PageTitle'
import classNames from 'classnames/bind'
import style from "./Cart.module.scss"
import { Button, Image, InputNumber, Table } from 'antd'
import { ColumnsType } from 'antd/es/table'
import { CloseOutlined, DollarOutlined } from '@ant-design/icons'
import ButtonCustom from '../../components/Button'
import Head from 'next/head'



const cx = classNames.bind(style)

interface DataType {
    key: string;
    product: string;
    name: string;
    price: number;
    quantity: number;
    subtotal: number;
    
}

export default function Cart() {
    const columns: ColumnsType<DataType> = [
        {
            title: ' ',
            dataIndex: 'delete',
            key: 'delete',
            width: 50,
            
            render: (_, record) => {
                return (
                    <>
                        <span  >
                            <CloseOutlined />
                        </span>
                    </>
                )
            }
            
        },
        {
            title: ' ',
            dataIndex: 'product',
            key: 'product',
            align: "center",
            width: 86,
            fixed: "left",
            render: (_, record) => {
                return (
                    <div className={cx("img-wrap")}>

                        <Image 
                        
                        src={require("../../assets/imgs/pasta.png").default.src}
                        fallback={require("../../assets/imgs/logo.png")}
                        
                        />
                    </div>
                )
            }
        },
        {
            title: 'product',
            dataIndex: 'name',
            key: 'name',
            width: 400,
           
            render: (_, record) => {
                return (
                    <>
                       <span className={cx("product-name")}>{record.name}</span>
                    </>
                )
            }
        },
        {
            title: 'price',
            dataIndex: 'price',
            key: 'price',
            width: 130,
            render: (_, record) => {
                return (
                    <>
                        <DollarOutlined style={{fontSize: '15px'}}/>
                        <span className={cx("product-price")}>{record.price}</span>
                    </>
                )
            }
        },
        {
            title: 'quantity',
            dataIndex: 'quantity',
            key: 'quantity',
            width: 260,
            render: (_, record) => {
                return (
                    <>
                        <InputNumber size='large' min={1} max={100} defaultValue={record.quantity} className={cx("product-quantity")}/>
                    </>
                )
            }
        },
        {
            title: 'subtotal',
            dataIndex: 'subtotal',
            key: 'subtotal',
            width: 180,
            render: (_, record) => {
                return (
                    <>
                        <DollarOutlined style={{fontSize: '15px'}}/>
                        <span className={cx("product-price")}>{record.subtotal}</span>
                    </>
                )
            }
        }
    ]
    const data: DataType[] = [
        {
            key: '1',
            product: "../../assets/imgs/pasta.png",
            name: "Pasta",
            price: 8.00,
            quantity: 1,
            subtotal: 8.00
        }
    ]
    
  return (
    <>
         <Head >
            <title>Fooce | Cart</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/icon.png" />
        </Head>
        <PageTitle name="Cart" />
        <div className={cx("cart")}>
            <Table columns={columns} dataSource={data} className={cx("cart-table")}/>
            <div className={cx("cart-total")}>
                <div className={cx("cart-title")}>
                        Cart totals
                </div>
                <div className={cx("total-item")}>
                        <div className={cx("total-title")}>Subtotal</div>
                        <div className={cx("total-infor")}>
                            <DollarOutlined style={{fontSize: "15px", color: "#9c9c9c", marginRight: "4px"}} />
                            47
                        </div>
                </div>
                <div className={cx("total-item")}>
                        <div className={cx("total-title")}>Shipping	</div>
                        <div className={cx("total-infor")}>	
                            <div >
                                Flat rate: { " "}
                                <DollarOutlined style={{fontSize: "15px", color: "#9c9c9c", marginRight: "4px"}} />
                                13
                            </div>
                            
                            <br />
                            <div >
                                 Shipping to <span className={cx("address")}>Vietnam</span> 
                            </div>
                           
                            <br />
                            <div className={cx("change-address")}>Change address</div>
                        </div>
                </div>
                <div className={cx("total-item")}>
                        <div className={cx("total-title")}>Total</div>
                        <div className={cx("total-infor")}>
                            <DollarOutlined style={{fontSize: "15px", color: "#9c9c9c", marginRight: "4px"}} />
                            60
                        </div>
                </div>
                <div style={{marginTop: "30px"}}>
                    <ButtonCustom name="proceed to checkout" />
                </div>
                
            </div>
        </div>
    </>
  )
}
