import Head from 'next/head'
import React from 'react'
import style from './Checkout.module.scss'
import classNames from 'classnames/bind'
import PageTitle from '../../components/PageTitle'
import { Cascader, Checkbox, Form, Input } from 'antd'
import ButtonCustom from '../../components/Button'


const cx = classNames.bind(style)

interface Option {
  value: string | number;
  label: string;
  children?: Option[];
}

const options: Option[] = [
  {
    value: 'HaNoi',
    label: 'Hà Nội',
    children: [
      {
        value: 'HoanKiemDistrict',
        label: 'Quận Hoàn Kiếm',
        children: [
          {
            value: 'ChuongDuongWard',
            label: 'Chương Dương',
          },
          {
            value: 'CuaDongWard',
            label: 'Cửa Đông',
          },
          {
            value: 'HangDaoWard',
            label: 'Hàng Đào',
          },
          {
            value: 'LyThaiToWard',
            label: 'Lý Thái Tổ',
          },
        ],
      },
      {
        value: 'BaDinhDistrict',
        label: 'Quận Ba Đình',
        children: [
          {
            value: 'DienBienWard',
            label: 'Điện Biên',
          },
          {
            value: 'DoiCanWard',
            label: 'Đội Cấn',
          },
          {
            value: 'KimMaWard',
            label: 'Kim Mã',
          },
          {
            value: 'QuanThanhWard',
            label: 'Quán Thánh',
          },
        ],
      },
      {
        value: 'DongAnhDistrict',
        label: 'Huyện Đông Anh',
        children: [
          {
            value: 'BacHongWard',
            label: 'Bắc Hồng',
          },
          {
            value: 'TTDongAnhWard',
            label: 'Thị Trấn Đông Anh',
          },
          {
            value: 'CoLoaWard',
            label: 'Cổ Loa',
          },
          {
            value: 'KimChungWard',
            label: 'Kim Chung',
          },
        ],
      },
      
    ],
  },
 
];
    const onChange = (value: string[]) => {
      console.log(value)
    }

export default function Checkout() {
    const onFinish = (values: any) => {
        console.log('Success:', values);
      };
      
      const onFinishFailed = (errorInfo: any) => {
        console.log('Failed:', errorInfo);
      };

      const onChange = (value: string[]) => {
        console.log(value)
      }
      const emailRules = [
        {
          type: 'email',
          message: 'Email address is not valid',
        },
        {
          required: true,
          message: 'Please input your email address!',
        },
      ];
      const phoneRules = [
        {
          pattern: /^[0-9]{10}$/,
          message: 'Invalid phone number. Please enter 10 digits',
        },
        {
          required: true,
          message: 'Please input your phone number',
        },
      ];
      
  return (
    <>
        <Head >
            <title>Fooce | Checkout</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/icon.png" />
        </Head>
        <PageTitle name="Checkout" />
        <div className={cx("checkout")}>
                <div className={cx("checkout-title")}>Billing details</div>
                <div className={cx("checkout-form")}>
                <Form
                    name="basic"
                    layout= "vertical"
                  
                    labelCol={{ span: 8 }}
                    wrapperCol={{ span: 16 }}
                   
                    initialValues={{ remember: true }}
                    onFinish={onFinish}
                    onFinishFailed={onFinishFailed}
                    autoComplete="off"
                    className={cx("form")}
                >
                    <Form.Item
                    label="Name"
                    name="name"
                    rules={[{ required: true, message: 'Please input your name!' }]}
                    className={cx("form-label")}
                    wrapperCol={{ span: 24 }}
                    >
                    <Input className={cx("form-input")}/>
                    </Form.Item>
                    <br />
                    <Form.Item
                        label="Email"
                        name="email"
                        rules={emailRules}
                        className={cx("form-label")}
                        wrapperCol={{ span: 24 }}
                    >
                    <Input className={cx("form-input")}/>
                    </Form.Item>
                    <br />
                    <Form.Item
                        label="Phone"
                        name="Phone"
                        rules={phoneRules}
                        className={cx("form-label")}
                        wrapperCol={{ span: 24 }}
                    >
                    <Input className={cx("form-input")}/>
                    </Form.Item>
                    <br />
                    <Form.Item
                        label="Address"
                        name="Address"
                        rules={[{ required: true, message: 'Please input your address!' }]}
                        className={cx("form-label")}
                        wrapperCol={{ span: 24 }}
                    >
                    
                      <Cascader options={options} onChange={onChange}  placeholder="Please select your address"/>
                    </Form.Item>
                    <Form.Item wrapperCol={{ span: 24 }}>
                        <ButtonCustom name= "place order" htmlType="submit" />
                    </Form.Item>
                </Form>
                </div>
        </div>
    </>
    
  )
}
