import "../styles/globals.scss";
import Layout from "../module/layout/layout";
import { useRouter } from "next/router";
import {QueryClientProvider, QueryClient} from 'react-query'
import Head from "next/head";
import Routes from "../router";
import {AppProps} from "next/app";

const queryClient = new QueryClient()

export default function MyApp({
  Component,
  pageProps,
  router
}: AppProps): JSX.Element {

  return (
    <QueryClientProvider client={queryClient}>
      <>
        <Head>
              <title>Fooce</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/icon.png" />
        </Head>
        <Routes
          Component={Component}
          pageProps={pageProps}
          router={router}
        /> 
        
      </>
    </QueryClientProvider>
      
 
  );
}


