import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import Homepage from '../module/home'

// import NavBar from '../components/NavBar'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Fooce</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon.png" />
      </Head>
      <Homepage />
     
    </div>
    
  )
}
