import { Button, Col, Input, InputNumber, Row, Select, Slider, Space } from 'antd'
import Head from 'next/head'
import React, { useState } from 'react'
import PageTitle from '../../components/PageTitle'
import classNames from 'classnames/bind'
import style from "./Product.module.scss"
import Product from '../../components/product'
import { DollarCircleOutlined, SearchOutlined } from '@ant-design/icons'
import Search from 'antd/es/input/Search'



const cx = classNames.bind(style)
export default function Juice() {
  const [inputValue, setInputValue] = useState(1);
  const handleChange = (value: string) => {
    console.log(`selected ${value}`);
  };

  const onChange = (newValue: number) => {
    setInputValue(newValue);
  }
  return (
    <>
         <Head >
            <title>Fooce | Juice</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/icon.png" />
        </Head>
        <PageTitle name= "Juice" />
        <div className={cx("product")}>
            <Row justify={'space-between'}>
                <Col span={17} className="gutter-row">
                  <div className={cx("sort")}>
                        <div className={cx("product-number")}>
                              Showing 1–9 of 12 results
                        </div>
                        
                        <Space wrap>
                          <Select
                            defaultValue="default"
                            style={{ width: 200 }}
                            onChange={handleChange}
                            options={[
                              { label: 'Default sorting',value : 'default' },
                              { label: 'Sort by popularity', value: 'popularity' },
                              { label: 'Sort by average rating', value: 'rating' },
                              { label: 'Sort by latest', value: 'latest' },
                              { label: 'Sort by price: low to high', value: 'low' },
                              { label: 'Sort by price: high to low', value: 'high' },
                            ]}
                          />
                          
                        </Space>
                  </div>
                  <Row className={cx("row-product")} gutter={16}>
                    <Product name="juice" col={8}/>
                    <Product name="juice" col={8}/>
                    <Product name="juice" col={8}/>
                    <Product name="juice" col={8}/>
                    <Product name="juice" col={8}/>
                    <Product name="juice" col={8}/>
                  </Row>
                </Col>
                <Col span={6} className="gutter-row">
                <div className={cx('filter-price')}>
                  Filter by price
                </div>
                <Row justify='space-between'>
                  <Col span={16}>
                    <Slider
                      min={0}
                      max={40}
                      step={10}
                      onChange={onChange}
                      value={typeof inputValue === 'number' ? inputValue : 0}
                      trackStyle={{backgroundColor: '#abe9b0'}}
                      railStyle={{backgroundColor: '#E5E5E5'}}
                      handleStyle={{}}
                    />
                    </Col>
                    <Col span={6}>
                      <InputNumber
                        min={0}
                        max={40}
                        style={{width: '50px'}}
                        value={inputValue}
                        onChange={onChange}
                      />
                    </Col>
                </Row>
                <div className={cx('price-range-wrap')}>
                  <div className={cx('price-range')}>
                    Price: <DollarCircleOutlined style={{color: '#5a5a5a', fontSize: '16px'}}/> 0 - <DollarCircleOutlined style={{color: '#5a5a5a', fontSize: '16px'}}/> {inputValue}
                  </div>
                  <Button className={cx('btn')}>filter</Button>
                </div>
                <div className={cx('product-category')}>
                  <div className={cx('filter-price')}>
                    Product categories
                  </div>
                    <div className={cx('category-item')}>
                        Colorful
                    </div>
                    <div className={cx('category-item')}>
                        Fruit Bowl
                    </div>
                    <div className={cx('category-item')}>
                        Healthy
                    </div>
                    <div className={cx('category-item')}>
                        Ice Cream
                    </div>
                    <div className={cx('category-item')}>
                        Mixed
                    </div>
                    <div className={cx('category-item')}>
                        Smoothie
                    </div>
                    <div className={cx('category-item')}>
                        Shakes
                    </div>
                </div>
                <div className={cx('product-search')}>
                  <Input size="large" placeholder="search product..." prefix={<SearchOutlined style={{color: '#abe9b0', fontWeight: '600', fontSize: '17px' }}/>} className={cx("search-input")}/>
                </div>
                </Col>
            </Row>
        </div>
    </>
  )
}
